# Semi-Structured Data Exploitation Zone

This notebook transforms cleaned semi-structured MongoDB collections into exploitation-ready analytical products.

The Trusted Zone stores normalized documents, but many fields are still nested JSON objects or arrays. The Exploitation Zone converts them into dimensions, facts, bridge tables, and denormalized marts for analysis.

## Purpose
Model trusted semi-structured weather and air-quality documents into MongoDB exploitation dimensions, facts, bridges, marts, and governance collections.

## Inputs
Trusted MongoDB collections such as `trusted_zone_semi-structured.airquality_barcelona` and `trusted_zone_semi-structured.weather_barcelona`.

## Validation / quality checks
The notebook validates source collections, non-empty exploitation collections, metadata completeness, key uniqueness where applicable, and governance collection writes.

## Transformation / cleaning logic
Nested station, sensor, instrument, license, weather, and availability structures are flattened or enriched into analytical MongoDB collections.

## Metadata and lineage fields
Outputs include `source_system`, `source_assets`, `created_at`, `schema_version`, `exploitation_asset_type`, catalogue records, quality summary records, and lineage records.

## Output assets
MongoDB collections in `exploitation_zone_semi_structured`, including `dim_*`, `bridge_*`, `fact_*`, `mart_*`, `exploitation_catalogue`, `exploitation_quality_summary`, and `exploitation_lineage`.

## RBAC / service user used
The production DAG uses MongoDB trusted/exploitation service users configured through environment variables.

## Notebook-DAG alignment note
This notebook mirrors `exploitation_zone_semistructured` without importing DAG functions. If notebook inputs come from aggregation/testing output while the DAG follows Trusted DAG Kafka date-partitioned output, that difference is intentional report evidence rather than a logic change.

## Execution Notes and Batch Logging
This notebook transforms trusted MongoDB weather and air-quality collections into exploitation dimensions, facts, marts, and governance collections. Mongo writes are logged in document batches, while validation and preview loops print collection names and counts for review.

## 1. Exploitation Design

Semi-structured exploitation focuses on three operations:

- **Flatten nested objects**: for example, `country.name`, `provider.name`, `coordinates.latitude`.
- **Explode arrays**: for example, station `sensors`, `instruments`, and `licenses`.
- **Create analytical marts**: query-friendly collections for station catalogues, sensor coverage, and weather time-series analysis.

| Output Type | Collections | Purpose |
|---|---|---|
| Dimensions | `dim_station`, `dim_country`, `dim_provider`, `dim_owner`, `dim_sensor`, `dim_instrument`, `dim_license`, `dim_weather_code` | Describe reusable analytical entities. |
| Facts | `fact_weather_observation`, `fact_station_availability` | Store measurable observations and station coverage metrics. |
| Bridge Tables | `bridge_station_sensor`, `bridge_station_instrument`, `bridge_station_license` | Resolve one-to-many relationships from nested arrays. |
| Marts | `mart_station_sensor_catalog`, `mart_weather_timeseries`, `mart_weather_summary`, `mart_environment_barcelona_overview` | Provide dashboard-ready denormalized datasets. |

## 2. Environment Setup

In [1]:
# Import libraries used for MongoDB access, JSON parsing, and tabular transformations.
import json
import hashlib
from datetime import datetime, timezone

import pandas as pd
from pymongo import MongoClient

# Source database: cleaned semi-structured documents from the Trusted Zone.
TRUSTED_DB = "trusted_zone_semi-structured"

# Target database: exploitation-ready semi-structured analytical products.
EXPLOITATION_DB = "exploitation_zone_semi_structured"

# Notebook-local metadata constants mirroring the semi-structured exploitation DAG.
EXPLOITATION_CREATED_AT = datetime.now(timezone.utc).isoformat()
EXPLOITATION_SCHEMA_VERSION = "exploitation_semistructured_v1"

# Create MongoDB clients for both zones.
mongo_client = MongoClient("mongodb://mongo:mongo@mongo:27017")
trusted_db = mongo_client[TRUSTED_DB]
exploitation_db = mongo_client[EXPLOITATION_DB]

print(f"Connected to MongoDB. Source: {TRUSTED_DB} | Target: {EXPLOITATION_DB}")

Connected to MongoDB. Source: trusted_zone_semi-structured | Target: exploitation_zone_semi_structured

## 3. Trusted Collection Validation

The semi-structured Trusted Zone currently contains two Barcelona collections:

| Collection | Content | Exploitation Role |
|---|---|---|
| `airquality_barcelona` | Station metadata with nested country, owner, provider, coordinates, sensors, instruments, licenses, and availability dates. | Source for station, sensor, provider, owner, country, license dimensions and bridge tables. |
| `weather_barcelona` | Weather observations with timestamp, temperature, wind speed, wind direction, weather code, interval, and day/night flag. | Source for weather observation facts and time-series marts. |

In [2]:
# Validate expected trusted collections before building exploitation outputs.
expected_collections = ["airquality_barcelona", "weather_barcelona"]
available_collections = trusted_db.list_collection_names()

for batch_no, collection_name in enumerate(expected_collections, start=1):
    if collection_name not in available_collections:
        raise ValueError(f"Missing trusted collection: {collection_name}")
    row_count = trusted_db[collection_name].count_documents({})
    print(f"[trusted collection batch {batch_no}/{len(expected_collections)}] {collection_name:<28} {row_count:>8,} documents")

[trusted collection batch 1/2] airquality_barcelona               66 documents
[trusted collection batch 2/2] weather_barcelona                  22 documents

## 4. Helper Functions

In [3]:
# Define reusable helpers for parsing JSON-like fields and writing clean MongoDB collections.
def parse_json_value(value, default=None):
    """Parse a JSON string, dict, or list. Return default when the value is empty or invalid."""
    if value is None:
        return default
    if isinstance(value, (dict, list)):
        return value
    if isinstance(value, str):
        text = value.strip()
        if not text:
            return default
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            return default
    return default


def stable_key(*parts):
    """Create a stable string key when the source does not provide a clean identifier."""
    joined = "|".join("" if part is None else str(part) for part in parts)
    return hashlib.sha1(joined.encode("utf-8")).hexdigest()


def parse_datetime_object(value):
    """Extract UTC and local timestamps from a nested datetime object or JSON string."""
    parsed = parse_json_value(value, default={})
    if not isinstance(parsed, dict):
        return None, None
    return parsed.get("utc"), parsed.get("local")


def parse_iso_datetime(value):
    """Parse ISO-like timestamp strings into pandas timestamps."""
    if value is None:
        return pd.NaT
    return pd.to_datetime(str(value).replace("Z", "+00:00"), errors="coerce")


def clean_records(records):
    """Convert pandas NaN/NaT values into None so MongoDB receives clean documents."""
    cleaned = []
    for record in records:
        out = {}
        for key, value in record.items():
            if pd.isna(value) if not isinstance(value, (list, dict)) else False:
                out[key] = None
            elif isinstance(value, pd.Timestamp):
                out[key] = value.isoformat()
            else:
                out[key] = value
        cleaned.append(out)
    return cleaned


def exploitation_asset_type(collection_name):
    if collection_name.startswith("dim_"):
        return "dimension"
    if collection_name.startswith("fact_"):
        return "fact"
    if collection_name.startswith("bridge_"):
        return "bridge"
    if collection_name.startswith("mart_"):
        return "mart"
    return "metric"


def write_collection(collection_name, dataframe, source_assets=None):
    """Replace one exploitation collection with the contents of a DataFrame."""
    output_df = dataframe.copy()
    output_df["source_system"] = "trusted-zone"
    output_df["source_assets"] = source_assets or ",".join(expected_collections)
    output_df["created_at"] = EXPLOITATION_CREATED_AT
    output_df["schema_version"] = EXPLOITATION_SCHEMA_VERSION
    output_df["exploitation_asset_type"] = exploitation_asset_type(collection_name)
    collection = exploitation_db[collection_name]
    collection.delete_many({})
    records = clean_records(output_df.to_dict("records")) if not output_df.empty else []
    print(f"[mongo write] {collection_name}: prepared {len(records):,} documents")
    if records:
        batch_size = 5000
        total_batches = (len(records) + batch_size - 1) // batch_size
        for batch_no, start in enumerate(range(0, len(records), batch_size), start=1):
            batch_records = records[start:start + batch_size]
            collection.insert_many(batch_records, ordered=False)
            print(f"[mongo write batch {batch_no}/{total_batches}] {collection_name}: inserted {len(batch_records)} documents")
    print(f"Created {collection_name:<42} {len(records):>8,} documents")

## 5. Load Trusted Documents

In [4]:
# Load trusted MongoDB collections into pandas DataFrames for semi-structured transformations.
airquality_df = pd.DataFrame(list(trusted_db["airquality_barcelona"].find({}, {"_id": 0})))
weather_df = pd.DataFrame(list(trusted_db["weather_barcelona"].find({}, {"_id": 0})))

# Remove exact duplicate trusted records to avoid duplicate exploitation outputs.
airquality_df = airquality_df.drop_duplicates().reset_index(drop=True)
weather_df = weather_df.drop_duplicates().reset_index(drop=True)

print(f"[trusted load batch 1/2] airquality records: {len(airquality_df):,}")
print(f"[trusted load batch 2/2] weather records:    {len(weather_df):,}")

[trusted load batch 1/2] airquality records: 3
[trusted load batch 2/2] weather records:    2

## 6. Dimension Tables

Dimensions describe reusable entities extracted from the nested semi-structured documents.

| Collection | Grain | Purpose |
|---|---|---|
| `dim_station` | One row per air-quality station | Stores station identity, location, source organization, monitoring flags, coordinates, and availability timestamps. |
| `dim_country` | One row per country | Stores country metadata extracted from nested station documents. |
| `dim_provider` | One row per data provider | Describes the organization providing station data. |
| `dim_owner` | One row per owner | Describes the station owner or responsible organization. |
| `dim_sensor` | One row per sensor | Stores sensor and pollutant/parameter metadata exploded from station sensor arrays. |
| `dim_instrument` | One row per instrument | Stores instrument types used by stations. |
| `dim_license` | One row per license | Stores data license metadata. |
| `dim_weather_code` | One row per WMO weather code | Adds readable labels for weather condition codes. |

In [5]:
# Flatten station-level nested objects into reusable station, country, provider, and owner dimensions.
station_rows = []
country_rows = []
provider_rows = []
owner_rows = []

for _, row in airquality_df.iterrows():
    country = parse_json_value(row.get("country"), default={}) or {}
    provider = parse_json_value(row.get("provider"), default={}) or {}
    owner = parse_json_value(row.get("owner"), default={}) or {}
    coordinates = parse_json_value(row.get("coordinates"), default={}) or {}
    sensors = parse_json_value(row.get("sensors"), default=[]) or []
    instruments = parse_json_value(row.get("instruments"), default=[]) or []
    licenses = parse_json_value(row.get("licenses"), default=[]) or []
    datetime_first_utc, datetime_first_local = parse_datetime_object(row.get("datetimeFirst"))
    datetime_last_utc, datetime_last_local = parse_datetime_object(row.get("datetimeLast"))

    station_rows.append({
        "station_id": row.get("id"),
        "station_name": row.get("name"),
        "locality": row.get("locality"),
        "timezone": row.get("timezone"),
        "country_id": country.get("id"),
        "provider_id": provider.get("id"),
        "owner_id": owner.get("id"),
        "is_mobile": row.get("isMobile"),
        "is_monitor": row.get("isMonitor"),
        "latitude": coordinates.get("latitude"),
        "longitude": coordinates.get("longitude"),
        "bounds": row.get("bounds"),
        "distance": row.get("distance"),
        "sensor_count": len(sensors) if isinstance(sensors, list) else 0,
        "instrument_count": len(instruments) if isinstance(instruments, list) else 0,
        "license_count": len(licenses) if isinstance(licenses, list) else 0,
        "datetime_first_utc": datetime_first_utc,
        "datetime_first_local": datetime_first_local,
        "datetime_last_utc": datetime_last_utc,
        "datetime_last_local": datetime_last_local,
    })

    if country:
        country_rows.append({"country_id": country.get("id"), "country_code": country.get("code"), "country_name": country.get("name")})
    if provider:
        provider_rows.append({"provider_id": provider.get("id"), "provider_name": provider.get("name")})
    if owner:
        owner_rows.append({"owner_id": owner.get("id"), "owner_name": owner.get("name")})

dim_station = pd.DataFrame(station_rows).drop_duplicates(subset=["station_id"]).reset_index(drop=True)
dim_country = pd.DataFrame(country_rows).drop_duplicates(subset=["country_id"]).reset_index(drop=True)
dim_provider = pd.DataFrame(provider_rows).drop_duplicates(subset=["provider_id"]).reset_index(drop=True)
dim_owner = pd.DataFrame(owner_rows).drop_duplicates(subset=["owner_id"]).reset_index(drop=True)

write_collection("dim_station", dim_station)
write_collection("dim_country", dim_country)
write_collection("dim_provider", dim_provider)
write_collection("dim_owner", dim_owner)

[mongo write] dim_station: prepared 3 documents
[mongo write batch 1/1] dim_station: inserted 3 documents
Created dim_station                                       3 documents
[mongo write] dim_country: prepared 1 documents
[mongo write batch 1/1] dim_country: inserted 1 documents
Created dim_country                                       1 documents
[mongo write] dim_provider: prepared 2 documents
[mongo write batch 1/1] dim_provider: inserted 2 documents
Created dim_provider                                      2 documents
[mongo write] dim_owner: prepared 1 documents
[mongo write batch 1/1] dim_owner: inserted 1 documents
Created dim_owner                                         1 documents

In [6]:
# Explode nested sensors, instruments, and licenses into dimensions plus bridge tables.
sensor_rows = []
station_sensor_rows = []
instrument_rows = []
station_instrument_rows = []
license_rows = []
station_license_rows = []

for _, row in airquality_df.iterrows():
    station_id = row.get("id")
    sensors = parse_json_value(row.get("sensors"), default=[]) or []
    instruments = parse_json_value(row.get("instruments"), default=[]) or []
    licenses = parse_json_value(row.get("licenses"), default=[]) or []

    for sensor in sensors if isinstance(sensors, list) else []:
        parameter = sensor.get("parameter", {}) if isinstance(sensor, dict) else {}
        sensor_id = sensor.get("id") if isinstance(sensor, dict) else None
        sensor_rows.append({
            "sensor_id": sensor_id,
            "sensor_name": sensor.get("name") if isinstance(sensor, dict) else None,
            "parameter_id": parameter.get("id") if isinstance(parameter, dict) else None,
            "parameter_name": parameter.get("name") if isinstance(parameter, dict) else None,
            "parameter_units": parameter.get("units") if isinstance(parameter, dict) else None,
            "parameter_display_name": parameter.get("displayName") if isinstance(parameter, dict) else None,
        })
        station_sensor_rows.append({"station_id": station_id, "sensor_id": sensor_id})

    for instrument in instruments if isinstance(instruments, list) else []:
        instrument_id = instrument.get("id") if isinstance(instrument, dict) else None
        instrument_rows.append({"instrument_id": instrument_id, "instrument_name": instrument.get("name") if isinstance(instrument, dict) else None})
        station_instrument_rows.append({"station_id": station_id, "instrument_id": instrument_id})

    for license_doc in licenses if isinstance(licenses, list) else []:
        license_id = license_doc.get("id") if isinstance(license_doc, dict) else None
        license_rows.append({"license_id": license_id, "license_name": license_doc.get("name") if isinstance(license_doc, dict) else None})
        station_license_rows.append({"station_id": station_id, "license_id": license_id})

dim_sensor = pd.DataFrame(sensor_rows).drop_duplicates(subset=["sensor_id"]).reset_index(drop=True)
bridge_station_sensor = pd.DataFrame(station_sensor_rows).drop_duplicates().reset_index(drop=True)
dim_instrument = pd.DataFrame(instrument_rows).drop_duplicates(subset=["instrument_id"]).reset_index(drop=True)
bridge_station_instrument = pd.DataFrame(station_instrument_rows).drop_duplicates().reset_index(drop=True)
dim_license = pd.DataFrame(license_rows).drop_duplicates(subset=["license_id"]).reset_index(drop=True)
bridge_station_license = pd.DataFrame(station_license_rows).drop_duplicates().reset_index(drop=True)

write_collection("dim_sensor", dim_sensor)
write_collection("bridge_station_sensor", bridge_station_sensor)
write_collection("dim_instrument", dim_instrument)
write_collection("bridge_station_instrument", bridge_station_instrument)
write_collection("dim_license", dim_license)
write_collection("bridge_station_license", bridge_station_license)

[mongo write] dim_sensor: prepared 20 documents
[mongo write batch 1/1] dim_sensor: inserted 20 documents
Created dim_sensor                                       20 documents
[mongo write] bridge_station_sensor: prepared 20 documents
[mongo write batch 1/1] bridge_station_sensor: inserted 20 documents
Created bridge_station_sensor                            20 documents
[mongo write] dim_instrument: prepared 1 documents
[mongo write batch 1/1] dim_instrument: inserted 1 documents
Created dim_instrument                                    1 documents
[mongo write] bridge_station_instrument: prepared 3 documents
[mongo write batch 1/1] bridge_station_instrument: inserted 3 documents
Created bridge_station_instrument                         3 documents
[mongo write] dim_license: prepared 2 documents
[mongo write batch 1/1] dim_license: inserted 2 documents
Created dim_license                                       2 documents
[mongo write] bridge_station_license: prepared 3 documents
[mongo write batch 1/1] bridge_station_license: inserted 3 documents
Created bridge_station_license                            3 documents

In [7]:
# Create a readable weather-code dimension using common WMO weather interpretation labels.
weather_code_labels = {
    0: "Clear sky",
    1: "Mainly clear",
    2: "Partly cloudy",
    3: "Overcast",
    45: "Fog",
    48: "Depositing rime fog",
    51: "Light drizzle",
    53: "Moderate drizzle",
    55: "Dense drizzle",
    61: "Slight rain",
    63: "Moderate rain",
    65: "Heavy rain",
    71: "Slight snow fall",
    73: "Moderate snow fall",
    75: "Heavy snow fall",
    80: "Slight rain showers",
    81: "Moderate rain showers",
    82: "Violent rain showers",
    95: "Thunderstorm",
}

dim_weather_code = pd.DataFrame([
    {"weathercode": int(code), "weather_description": weather_code_labels.get(int(code), "Unknown")}
    for code in sorted(weather_df["weathercode"].dropna().unique())
])

write_collection("dim_weather_code", dim_weather_code)

[mongo write] dim_weather_code: prepared 1 documents
[mongo write batch 1/1] dim_weather_code: inserted 1 documents
Created dim_weather_code                                  1 documents

## 7. Fact Tables

Fact collections store observable or measurable records at a clear grain.

| Collection | Grain | Purpose |
|---|---|---|
| `fact_weather_observation` | One weather record per timestamp | Stores weather time-series measurements such as temperature, wind speed, wind direction, weather code, and day/night flag. |
| `fact_station_availability` | One row per station | Stores station coverage metrics such as first/last available timestamps, active days, and counts of sensors, instruments, and licenses. |

In [8]:
# Build a weather observation fact table and enrich timestamps with date and hour fields.
fact_weather_observation = weather_df.copy()
fact_weather_observation["observation_time"] = pd.to_datetime(fact_weather_observation["time"], errors="coerce")
fact_weather_observation["observation_date"] = fact_weather_observation["observation_time"].dt.date.astype(str)
fact_weather_observation["observation_hour"] = fact_weather_observation["observation_time"].dt.hour
fact_weather_observation["observation_id"] = fact_weather_observation.apply(
    lambda row: stable_key(row.get("time"), row.get("temperature"), row.get("windspeed"), row.get("weathercode")),
    axis=1,
)
fact_weather_observation = fact_weather_observation[[
    "observation_id",
    "observation_time",
    "observation_date",
    "observation_hour",
    "interval",
    "is_day",
    "temperature",
    "weathercode",
    "winddirection",
    "windspeed",
]]

write_collection("fact_weather_observation", fact_weather_observation)

[mongo write] fact_weather_observation: prepared 2 documents
[mongo write batch 1/1] fact_weather_observation: inserted 2 documents
Created fact_weather_observation                          2 documents

In [9]:
# Build station availability facts from station metadata and nested availability timestamps.
fact_station_availability = dim_station.copy()
fact_station_availability["datetime_first_parsed"] = fact_station_availability["datetime_first_utc"].apply(parse_iso_datetime)
fact_station_availability["datetime_last_parsed"] = fact_station_availability["datetime_last_utc"].apply(parse_iso_datetime)
fact_station_availability["active_days"] = (
    fact_station_availability["datetime_last_parsed"] - fact_station_availability["datetime_first_parsed"]
).dt.days
fact_station_availability = fact_station_availability[[
    "station_id",
    "datetime_first_utc",
    "datetime_last_utc",
    "active_days",
    "is_mobile",
    "is_monitor",
    "sensor_count",
    "instrument_count",
    "license_count",
]]

write_collection("fact_station_availability", fact_station_availability)

[mongo write] fact_station_availability: prepared 3 documents
[mongo write batch 1/1] fact_station_availability: inserted 3 documents
Created fact_station_availability                         3 documents

## 8. Denormalized Analytical Marts

Marts are designed for direct consumption by dashboards and reports.

| Collection | Grain | Purpose |
|---|---|---|
| `mart_station_sensor_catalog` | One row per station-sensor pair | Combines station, provider, owner, country, coordinates, and sensor metadata for station catalogue analysis. |
| `mart_weather_timeseries` | One row per weather observation | Provides clean weather measurements with readable weather labels for plotting time-series. |
| `mart_weather_summary` | One row per date and hour | Aggregates weather observations into hourly summaries. |
| `mart_environment_barcelona_overview` | One overview row | Summarizes station coverage, sensor coverage, latest weather, and average weather values for Barcelona. |

In [10]:
# Create a station-sensor catalogue mart by joining station metadata with exploded sensor metadata.
mart_station_sensor_catalog = (
    bridge_station_sensor
    .merge(dim_station, on="station_id", how="left")
    .merge(dim_sensor, on="sensor_id", how="left")
    .merge(dim_country, on="country_id", how="left")
    .merge(dim_provider, on="provider_id", how="left")
    .merge(dim_owner, on="owner_id", how="left")
)

mart_station_sensor_catalog = mart_station_sensor_catalog[[
    "station_id",
    "station_name",
    "locality",
    "timezone",
    "country_code",
    "country_name",
    "provider_name",
    "owner_name",
    "is_mobile",
    "is_monitor",
    "latitude",
    "longitude",
    "bounds",
    "distance",
    "sensor_id",
    "sensor_name",
    "parameter_name",
    "parameter_units",
    "parameter_display_name",
    "datetime_first_utc",
    "datetime_last_utc",
]]

write_collection("mart_station_sensor_catalog", mart_station_sensor_catalog)

[mongo write] mart_station_sensor_catalog: prepared 20 documents
[mongo write batch 1/1] mart_station_sensor_catalog: inserted 20 documents
Created mart_station_sensor_catalog                      20 documents

In [11]:
# Create weather marts for raw time-series plotting and hourly summary analysis.
mart_weather_timeseries = fact_weather_observation.merge(dim_weather_code, on="weathercode", how="left")

mart_weather_summary = (
    mart_weather_timeseries
    .groupby(["observation_date", "observation_hour"], dropna=False)
    .agg(
        avg_temperature=("temperature", "mean"),
        min_temperature=("temperature", "min"),
        max_temperature=("temperature", "max"),
        avg_windspeed=("windspeed", "mean"),
        max_windspeed=("windspeed", "max"),
        observation_count=("observation_id", "count"),
        day_observation_count=("is_day", lambda values: int((values == 1).sum())),
        night_observation_count=("is_day", lambda values: int((values == 0).sum())),
    )
    .reset_index()
)

write_collection("mart_weather_timeseries", mart_weather_timeseries)
write_collection("mart_weather_summary", mart_weather_summary)

[mongo write] mart_weather_timeseries: prepared 2 documents
[mongo write batch 1/1] mart_weather_timeseries: inserted 2 documents
Created mart_weather_timeseries                           2 documents
[mongo write] mart_weather_summary: prepared 1 documents
[mongo write batch 1/1] mart_weather_summary: inserted 1 documents
Created mart_weather_summary                              1 documents

In [12]:
# Create one high-level overview mart for a Barcelona environmental dashboard.
latest_weather = mart_weather_timeseries.sort_values("observation_time").tail(1)
latest_row = latest_weather.iloc[0].to_dict() if not latest_weather.empty else {}

mart_environment_barcelona_overview = pd.DataFrame([{
    "locality": "Barcelona",
    "station_count": int(dim_station["station_id"].nunique()),
    "sensor_count": int(dim_sensor["sensor_id"].nunique()),
    "provider_count": int(dim_provider["provider_id"].nunique()),
    "owner_count": int(dim_owner["owner_id"].nunique()),
    "avg_temperature": float(mart_weather_timeseries["temperature"].mean()) if not mart_weather_timeseries.empty else None,
    "avg_windspeed": float(mart_weather_timeseries["windspeed"].mean()) if not mart_weather_timeseries.empty else None,
    "latest_weather_time": latest_row.get("observation_time"),
    "latest_temperature": latest_row.get("temperature"),
    "latest_weathercode": latest_row.get("weathercode"),
    "latest_weather_description": latest_row.get("weather_description"),
}])

write_collection("mart_environment_barcelona_overview", mart_environment_barcelona_overview)

[mongo write] mart_environment_barcelona_overview: prepared 1 documents
[mongo write batch 1/1] mart_environment_barcelona_overview: inserted 1 documents
Created mart_environment_barcelona_overview               1 documents

## 9. Validation and Preview

In [13]:
# Validate all exploitation collections and preview the most important marts.
collections_to_validate = sorted(exploitation_db.list_collection_names())
for batch_no, collection_name in enumerate(collections_to_validate, start=1):
    count = exploitation_db[collection_name].count_documents({})
    print(f"[collection validation batch {batch_no}/{len(collections_to_validate)}] {collection_name:<42} {count:>8,} documents")

[collection validation batch 1/17] bridge_station_instrument                         3 documents
[collection validation batch 2/17] bridge_station_license                            3 documents
[collection validation batch 3/17] bridge_station_sensor                            20 documents
[collection validation batch 4/17] dim_country                                       1 documents
[collection validation batch 5/17] dim_instrument                                    1 documents
[collection validation batch 6/17] dim_license                                       2 documents
[collection validation batch 7/17] dim_owner                                         1 documents
[collection validation batch 8/17] dim_provider                                      2 documents
[collection validation batch 9/17] dim_sensor                                       20 documents
[collection validation batch 10/17] dim_station                                       3 documents
[collection validation batch 11/17] dim_weather_code                                  1 documents
[collection validation batch 12/17] fact_station_availability                         3 documents
[collection validation batch 13/17] fact_weather_observation                          2 documents
[collection validation batch 14/17] mart_environment_barcelona_overview               1 documents
[collection validation batch 15/17] mart_station_sensor_catalog                      20 documents
[collection validation batch 16/17] mart_weather_summary                              1 documents
[collection validation batch 17/17] mart_weather_timeseries                           2 documents

In [14]:
# Display small samples from the main analytical marts for human validation.
preview_collections = [
    "mart_station_sensor_catalog",
    "mart_weather_timeseries",
    "mart_weather_summary",
    "mart_environment_barcelona_overview",
]

for batch_no, collection_name in enumerate(preview_collections, start=1):
    print(f"\n[preview batch {batch_no}/{len(preview_collections)}] {collection_name}")
    display(pd.DataFrame(list(exploitation_db[collection_name].find({}, {"_id": 0}).limit(5))))

[preview batch 1/4] mart_station_sensor_catalog

,station_id,station_name,locality,timezone,country_code,country_name,provider_name,owner_name,is_mobile,is_monitor,...,parameter_name,parameter_units,parameter_display_name,datetime_first_utc,datetime_last_utc,source_system,source_assets,created_at,schema_version,exploitation_asset_type
0,2990,barcelona (parc de la vall d'hebron),barcelona,europe/madrid,ES,Spain,EEA,Unknown Governmental Organization,None,None,...,co,µg/m³,CO mass,None,None,trusted-zone,"airquality_barcelona,weather_barcelona",2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1,mart
1,2990,barcelona (parc de la vall d'hebron),barcelona,europe/madrid,ES,Spain,EEA,Unknown Governmental Organization,None,None,...,no,µg/m³,NO mass,None,None,trusted-zone,"airquality_barcelona,weather_barcelona",2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1,mart
2,2990,barcelona (parc de la vall d'hebron),barcelona,europe/madrid,ES,Spain,EEA,Unknown Governmental Organization,None,None,...,no2,µg/m³,NO₂ mass,None,None,trusted-zone,"airquality_barcelona,weather_barcelona",2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1,mart
3,2990,barcelona (parc de la vall d'hebron),barcelona,europe/madrid,ES,Spain,EEA,Unknown Governmental Organization,None,None,...,nox,µg/m³,NOx mass,None,None,trusted-zone,"airquality_barcelona,weather_barcelona",2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1,mart
4,2990,barcelona (parc de la vall d'hebron),barcelona,europe/madrid,ES,Spain,EEA,Unknown Governmental Organization,None,None,...,o3,µg/m³,O₃ mass,None,None,trusted-zone,"airquality_barcelona,weather_barcelona",2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1,mart

[preview batch 2/4] mart_weather_timeseries

,observation_id,observation_time,observation_date,observation_hour,interval,is_day,temperature,weathercode,winddirection,windspeed,weather_description,source_system,source_assets,created_at,schema_version,exploitation_asset_type
0,9a9755ebd16aaba0b33c9744e359fc8f464c07b0,2026-06-06T16:30:00,2026-06-06,16,900,1,23.8,1,206,9.2,Mainly clear,trusted-zone,"airquality_barcelona,weather_barcelona",2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1,mart
1,634e2a592a005d2b21920dec653f6e704faf82d6,2026-06-06T16:45:00,2026-06-06,16,900,1,23.8,1,204,8.7,Mainly clear,trusted-zone,"airquality_barcelona,weather_barcelona",2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1,mart

[preview batch 3/4] mart_weather_summary

,observation_date,observation_hour,avg_temperature,min_temperature,max_temperature,avg_windspeed,max_windspeed,observation_count,day_observation_count,night_observation_count,source_system,source_assets,created_at,schema_version,exploitation_asset_type
0,2026-06-06,16,23.8,23.8,23.8,8.95,9.2,2,2,0,trusted-zone,"airquality_barcelona,weather_barcelona",2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1,mart

[preview batch 4/4] mart_environment_barcelona_overview

,locality,station_count,sensor_count,provider_count,owner_count,avg_temperature,avg_windspeed,latest_weather_time,latest_temperature,latest_weathercode,latest_weather_description,source_system,source_assets,created_at,schema_version,exploitation_asset_type
0,Barcelona,3,20,2,1,23.8,8.95,2026-06-06T16:45:00,23.8,1,Mainly clear,trusted-zone,"airquality_barcelona,weather_barcelona",2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1,mart

## 10. Exploitation Output Summary

This semi-structured exploitation notebook converts nested MongoDB documents into analytical products by:

- flattening station metadata into reusable dimensions,
- exploding nested arrays into bridge tables,
- building weather and station availability facts,
- creating dashboard-ready marts for station catalogue, weather time-series, weather summaries, and Barcelona environmental overview.

The implementation is dataset-specific because exploitation requires semantic knowledge of station metadata and weather observations, but it follows general semi-structured exploitation patterns.

## 11. Exploitation Governance Outputs

<!-- CODEX_EXPLOITATION_GOVERNANCE_SEMI -->

This section creates the same lightweight exploitation catalogue, quality summary, and lineage collections used by the production DAG. The notebook remains based on aggregation outputs, while the production DAG follows the Trusted MongoDB outputs.

### Governance Helper Functions

In [15]:
# CODEX_EXPLOITATION_GOVERNANCE_SEMI
# Build data-product catalogue, quality summary, and lineage collections for semi-structured exploitation outputs.

def governance_domain(asset_name):
    if "weather" in asset_name:
        return "barcelona_weather"
    if "station" in asset_name or "sensor" in asset_name or "air" in asset_name:
        return "barcelona_air_quality"
    return "barcelona_environment"


def governance_downstream_usage(asset_name):
    if asset_name.startswith("mart_"):
        return "environment dashboard and document queries"
    if asset_name.startswith("bridge_") or asset_name.startswith("dim_"):
        return "semi-structured analytical modelling support"
    return "semi-structured analyst queries"


def unique_key_field(asset_name):
    return {
        "dim_station": "station_id",
        "dim_country": "country_id",
        "dim_provider": "provider_id",
        "dim_owner": "owner_id",
        "dim_sensor": "sensor_id",
        "dim_instrument": "instrument_id",
        "dim_license": "license_id",
        "dim_weather_code": "weathercode",
        "fact_weather_observation": "observation_id",
    }.get(asset_name)


def quality_record(asset_name, check_name, status, observed_value, expected_value):
    return {
        "asset_name": asset_name,
        "check_name": check_name,
        "status": status,
        "observed_value": str(observed_value),
        "expected_value": expected_value,
        "created_at": EXPLOITATION_CREATED_AT,
        "schema_version": EXPLOITATION_SCHEMA_VERSION,
    }

business_collections = sorted(
    name for name in exploitation_db.list_collection_names()
    if name not in {"exploitation_catalogue", "exploitation_quality_summary", "exploitation_lineage"}
)
metadata_fields = ["source_system", "source_assets", "created_at", "schema_version", "exploitation_asset_type"]

### Build Governance Records

In [16]:
quality_records = []
catalogue_records = []
lineage_records = []
for batch_no, asset_name in enumerate(business_collections, start=1):
    collection = exploitation_db[asset_name]
    row_count = collection.count_documents({})
    print(f"[governance scan batch {batch_no}/{len(business_collections)}] {asset_name}: documents={row_count:,}")
    sample = collection.find_one({}, {"_id": 0}) or {}
    source_assets = sample.get("source_assets", ",".join(expected_collections))
    quality_records.append(quality_record(asset_name, "non_empty", "PASS" if row_count > 0 else "FAIL", row_count, "> 0"))
    missing_metadata = collection.count_documents({"$or": [{field: {"$in": [None, ""]}} for field in metadata_fields]})
    quality_records.append(quality_record(asset_name, "metadata_complete", "PASS" if missing_metadata == 0 else "FAIL", missing_metadata, "0 missing documents"))
    key_field = unique_key_field(asset_name)
    if key_field:
        distinct_count = len(collection.distinct(key_field))
        quality_records.append(quality_record(asset_name, "business_key_unique", "PASS" if distinct_count == row_count else "FAIL", f"{distinct_count}/{row_count}", "distinct=count"))
    catalogue_records.append({
        "asset_name": asset_name,
        "domain": governance_domain(asset_name),
        "asset_type": exploitation_asset_type(asset_name),
        "storage_system": "MongoDB",
        "location": f"{EXPLOITATION_DB}.{asset_name}",
        "source_system": "trusted-zone",
        "source_assets": source_assets,
        "downstream_usage": governance_downstream_usage(asset_name),
        "owner": "analytics",
        "record_count": row_count,
        "created_at": EXPLOITATION_CREATED_AT,
        "schema_version": EXPLOITATION_SCHEMA_VERSION,
    })
    lineage_records.append({
        "asset_name": asset_name,
        "upstream_zone": "trusted-zone",
        "upstream_assets": source_assets,
        "transformation_name": f"semistructured_exploitation.{asset_name}",
        "downstream_usage": governance_downstream_usage(asset_name),
        "created_at": EXPLOITATION_CREATED_AT,
        "schema_version": EXPLOITATION_SCHEMA_VERSION,
    })

quality_by_asset = {}
for record in quality_records:
    if record["status"] != "PASS":
        quality_by_asset[record["asset_name"]] = record["status"]
for record in catalogue_records:
    record["quality_status"] = quality_by_asset.get(record["asset_name"], "PASS")

[governance scan batch 1/17] bridge_station_instrument: documents=3
[governance scan batch 2/17] bridge_station_license: documents=3
[governance scan batch 3/17] bridge_station_sensor: documents=20
[governance scan batch 4/17] dim_country: documents=1
[governance scan batch 5/17] dim_instrument: documents=1
[governance scan batch 6/17] dim_license: documents=2
[governance scan batch 7/17] dim_owner: documents=1
[governance scan batch 8/17] dim_provider: documents=2
[governance scan batch 9/17] dim_sensor: documents=20
[governance scan batch 10/17] dim_station: documents=3
[governance scan batch 11/17] dim_weather_code: documents=1
[governance scan batch 12/17] fact_station_availability: documents=3
[governance scan batch 13/17] fact_weather_observation: documents=2
[governance scan batch 14/17] mart_environment_barcelona_overview: documents=1
[governance scan batch 15/17] mart_station_sensor_catalog: documents=20
[governance scan batch 16/17] mart_weather_summary: documents=1
[governance scan batch 17/17] mart_weather_timeseries: documents=2

### Write Governance Collections and Preview

In [17]:
governance_batches = {
    "exploitation_catalogue": catalogue_records,
    "exploitation_quality_summary": quality_records,
    "exploitation_lineage": lineage_records,
}
for batch_no, (collection_name, records) in enumerate(governance_batches.items(), start=1):
    print(f"[governance write batch {batch_no}/{len(governance_batches)}] {collection_name}: records={len(records)}")
    exploitation_db[collection_name].delete_many({})
    if records:
        exploitation_db[collection_name].insert_many(clean_records(records), ordered=False)
    print(f"Wrote {collection_name} documents={len(records)}")

pd.DataFrame(quality_records).sort_values(["asset_name", "check_name"])

[governance write batch 1/3] exploitation_catalogue: records=17
Wrote exploitation_catalogue documents=17
[governance write batch 2/3] exploitation_quality_summary: records=43
Wrote exploitation_quality_summary documents=43
[governance write batch 3/3] exploitation_lineage: records=17
Wrote exploitation_lineage documents=17

,asset_name,check_name,status,observed_value,expected_value,created_at,schema_version
1,bridge_station_instrument,metadata_complete,PASS,0,0 missing documents,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
0,bridge_station_instrument,non_empty,PASS,3,> 0,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
3,bridge_station_license,metadata_complete,PASS,0,0 missing documents,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
2,bridge_station_license,non_empty,PASS,3,> 0,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
5,bridge_station_sensor,metadata_complete,PASS,0,0 missing documents,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
4,bridge_station_sensor,non_empty,PASS,20,> 0,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
8,dim_country,business_key_unique,PASS,1/1,distinct=count,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
7,dim_country,metadata_complete,PASS,0,0 missing documents,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
6,dim_country,non_empty,PASS,1,> 0,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
11,dim_instrument,business_key_unique,PASS,1/1,distinct=count,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
10,dim_instrument,metadata_complete,PASS,0,0 missing documents,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
9,dim_instrument,non_empty,PASS,1,> 0,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
14,dim_license,business_key_unique,PASS,2/2,distinct=count,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
13,dim_license,metadata_complete,PASS,0,0 missing documents,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
12,dim_license,non_empty,PASS,2,> 0,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
17,dim_owner,business_key_unique,PASS,1/1,distinct=count,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
16,dim_owner,metadata_complete,PASS,0,0 missing documents,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
15,dim_owner,non_empty,PASS,1,> 0,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
20,dim_provider,business_key_unique,PASS,2/2,distinct=count,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
19,dim_provider,metadata_complete,PASS,0,0 missing documents,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
18,dim_provider,non_empty,PASS,2,> 0,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
23,dim_sensor,business_key_unique,PASS,20/20,distinct=count,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
22,dim_sensor,metadata_complete,PASS,0,0 missing documents,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
21,dim_sensor,non_empty,PASS,20,> 0,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
26,dim_station,business_key_unique,PASS,3/3,distinct=count,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
25,dim_station,metadata_complete,PASS,0,0 missing documents,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
24,dim_station,non_empty,PASS,3,> 0,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
29,dim_weather_code,business_key_unique,PASS,1/1,distinct=count,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
28,dim_weather_code,metadata_complete,PASS,0,0 missing documents,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
27,dim_weather_code,non_empty,PASS,1,> 0,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
31,fact_station_availability,metadata_complete,PASS,0,0 missing documents,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
30,fact_station_availability,non_empty,PASS,3,> 0,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
34,fact_weather_observation,business_key_unique,PASS,2/2,distinct=count,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
33,fact_weather_observation,metadata_complete,PASS,0,0 missing documents,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
32,fact_weather_observation,non_empty,PASS,2,> 0,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
36,mart_environment_barcelona_overview,metadata_complete,PASS,0,0 missing documents,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
35,mart_environment_barcelona_overview,non_empty,PASS,1,> 0,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
38,mart_station_sensor_catalog,metadata_complete,PASS,0,0 missing documents,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
37,mart_station_sensor_catalog,non_empty,PASS,20,> 0,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
40,mart_weather_summary,metadata_complete,PASS,0,0 missing documents,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
39,mart_weather_summary,non_empty,PASS,1,> 0,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
42,mart_weather_timeseries,metadata_complete,PASS,0,0 missing documents,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1
41,mart_weather_timeseries,non_empty,PASS,2,> 0,2026-06-06T17:10:13.665647+00:00,exploitation_semistructured_v1